---
name: Release
on:
  push:
    tags:
      - "*"
jobs:
  build:
    permissions:
      contents: write
    continue-on-error: false
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - uses: cargo-bins/cargo-binstall@main

      - name: Install the dependencies
        run: |
          sudo apt update
          sudo apt install -y podman binutils-aarch64-linux-gnu musl-tools
          cargo binstall -y cross

      - name: Build for arm64 musl
        run: |
          CROSS_CONTAINER_ENGINE=podman cross build --target aarch64-unknown-linux-musl --release
          cp target/aarch64-unknown-linux-musl/release/lobtui lobtui-aarch64-unknown-linux-musl

      - name: Build for x86_64 musl
        run: |
          CROSS_CONTAINER_ENGINE=podman cross build --target x86_64-unknown-linux-musl --release
          cp target/x86_64-unknown-linux-musl/release/lobtui lobtui-x86_64-unknown-linux-musl

      - name: Upload Binary
        uses: softprops/action-gh-release@v2
        with:
          files: "lobtui*"
          body: |
            [Release.md](${{ github.server_url }}/${{ github.repository }}/blob/main/Release.md)
